/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input sigA,
    input sigB,
    input sigCin,
    input [23:0] io_dip,
    output reg pin_outOne,
    output reg pin_outTwo,
    output reg pin_outThree
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [2:0] M_outputSig_d, M_outputSig_q = 1'h0;
  
  reg [9:0] abc;
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    pin_outOne = M_outputSig_q;
    pin_outTwo = M_outputSig_q;
    pin_outThree = M_outputSig_q;
    io_led[0+0+7-:8] = 8'h00;
    io_led[8+0+7-:8] = 8'h00;
    io_led[16+0+7-:8] = 8'h00;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[0+0+0-:1] = io_dip[0+0+0-:1];
    io_led[0+1+0-:1] = io_dip[8+0+0-:1];
    io_led[0+2+0-:1] = io_dip[16+0+0-:1];
    io_led[0+5+0-:1] = (io_dip[0+0+0-:1] & io_dip[8+0+0-:1]) | (io_dip[8+0+0-:1] & io_dip[16+0+0-:1]) | (io_dip[0+0+0-:1] & io_dip[16+0+0-:1]);
    abc[0+0-:1] = io_dip[0+0+0-:1] + io_dip[8+0+0-:1] + io_dip[16+0+0-:1];
    if (abc[0+0-:1] == 1'h1 | abc[0+0-:1] == 2'h3) begin
      io_led[0+6+0-:1] = io_dip[0+0+0-:1] | io_dip[8+0+0-:1] | io_dip[16+0+0-:1];
    end
  end
  
  always @(posedge clk) begin
    M_outputSig_q <= M_outputSig_d;
  end
  
endmodule
